"""Public STAR-CLIP package namespace."""

from adaptcliplib.adaptclip import (PQAdapter, TextualAdapter,
                                    VisionConditionedAnchorUpdater,
                                    VisualAdapter, VisualResidualAdapter,
                                    aggregate_patch_tokens_multiscale,
                                    compute_global_local_score_batchwise,
                                    fusion_fun)
from adaptcliplib.loss import (BinaryDiceLoss, FocalLoss,
                               patch_score_alignment_loss,
                               semantic_consistency_regularization_loss)
from adaptcliplib.model_load import available_models, load
from adaptcliplib.starclip import (STARCLIPDualAnchorModules,
                                   STARCLIP_MODULES_KEY, STARCLIP_PHASE_KEY,
                                   apply_source_memory_residual,
                                   apply_starclip_preset, binary_margin,
                                   bounded_residual,
                                   build_normal_context_feature,
                                   dual_anchor_margin_fusion,
                                   foreground_background_suppression,
                                   gaussian_smoothing_2d,
                                   legacy_linear_fusion,
                                   local_prob_two_class_from_margin,
                                   margin_to_two_class_logits,
                                   normalize_starclip_preset_name,
                                   normalize_two_class_probability,
                                   probability_to_margin,
                                   source_memory_anomaly_probability,
                                   source_patch_memory_from_features, topk_mean,
                                   uses_starclip)

__all__ = [
    "TextualAdapter",
    "VisualAdapter",
    "VisualResidualAdapter",
    "VisionConditionedAnchorUpdater",
    "STARCLIPDualAnchorModules",
    "apply_starclip_preset",
    "uses_starclip",
    "normalize_starclip_preset_name",
    "STARCLIP_MODULES_KEY",
    "STARCLIP_PHASE_KEY",
    "PQAdapter",
    "aggregate_patch_tokens_multiscale",
    "compute_global_local_score_batchwise",
    "fusion_fun",
    "binary_margin",
    "margin_to_two_class_logits",
    "probability_to_margin",
    "bounded_residual",
    "topk_mean",
    "build_normal_context_feature",
    "foreground_background_suppression",
    "source_patch_memory_from_features",
    "source_memory_anomaly_probability",
    "apply_source_memory_residual",
    "normalize_two_class_probability",
    "gaussian_smoothing_2d",
    "local_prob_two_class_from_margin",
    "legacy_linear_fusion",
    "dual_anchor_margin_fusion",
    "FocalLoss",
    "BinaryDiceLoss",
    "patch_score_alignment_loss",
    "semantic_consistency_regularization_loss",
    "load",
    "available_models",
]
