"""STAR-CLIP dual-anchor modules."""

from adaptcliplib.starclip import (STARCLIPDualAnchorModules,
                                   STARCLIP_MODULES_KEY, STARCLIP_PHASE_KEY,
                                   GlobalLocalImageScoreFusion,
                                   apply_source_memory_residual,
                                   apply_starclip_preset, binary_margin,
                                   bounded_residual,
                                   build_normal_context_feature,
                                   dual_anchor_margin_fusion,
                                   foreground_background_suppression,
                                   gaussian_smoothing_2d,
                                   legacy_linear_fusion,
                                   local_prob_two_class_from_margin,
                                   margin_to_two_class_logits,
                                   normalize_starclip_preset_name,
                                   normalize_two_class_probability,
                                   probability_to_margin,
                                   source_memory_anomaly_probability,
                                   source_patch_memory_from_features, topk_mean,
                                   uses_starclip)

__all__ = [
    "STARCLIPDualAnchorModules",
    "STARCLIP_MODULES_KEY",
    "STARCLIP_PHASE_KEY",
    "GlobalLocalImageScoreFusion",
    "apply_source_memory_residual",
    "apply_starclip_preset",
    "binary_margin",
    "bounded_residual",
    "build_normal_context_feature",
    "dual_anchor_margin_fusion",
    "foreground_background_suppression",
    "gaussian_smoothing_2d",
    "legacy_linear_fusion",
    "local_prob_two_class_from_margin",
    "margin_to_two_class_logits",
    "normalize_starclip_preset_name",
    "normalize_two_class_probability",
    "probability_to_margin",
    "source_memory_anomaly_probability",
    "source_patch_memory_from_features",
    "topk_mean",
    "uses_starclip",
]
